const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Physics,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Clipboard,
		C3.Plugins.progressbar,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.List,
		C3.Plugins.Particles,
		C3.Plugins.Button,
		C3.Plugins.Multiplayer,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.sliderbar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Eponesh_GameScore.Cnds.AchievementsPickAchievement,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAchievementsCurAchievementUnlocked,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsUnlock,
		C3.Plugins.Eponesh_GameScore.Exps.AchievementsCurAchievementID,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Eponesh_GameScore.Acts.AchievementsOpen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Multiplayer.Exps.FromAlias,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Multiplayer.Exps.HostID,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Multiplayer.Exps.HostAlias,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.TextBox.Acts.ScrollToBottom,
		C3.Plugins.Multiplayer.Exps.CurrentRoom,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.Multiplayer.Exps.PeerCount,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Multiplayer.Exps.PeerID,
		C3.Plugins.Multiplayer.Cnds.OnPeerDisconnected,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Multiplayer.Acts.KickPeer,
		C3.Plugins.Multiplayer.Cnds.OnHostDisconnected,
		C3.Plugins.Multiplayer.Cnds.SignallingIsInRoom,
		C3.Plugins.Multiplayer.Acts.SignallingLeaveRoom,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Acts.SignallingRequestRoomList,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.AdvancedRandom.Exps.Seed,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.TextBox.Acts.SetMaxLength,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetName,
		C3.Plugins.Button.Acts.SetChecked,
		C3.Plugins.Button.Cnds.IsChecked,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Opacity
	];
};
self.C3_JsPropNameTable = [
	{пол: 0},
	{Твёрдый: 0},
	{стены: 0},
	{лампа: 0},
	{стенапрозрачная: 0},
	{темнота: 0},
	{каменнаяСтена: 0},
	{каменныйпол: 0},
	{стены2: 0},
	{Переход: 0},
	{Стена: 0},
	{Трава: 0},
	{СВет: 0},
	{Камушки: 0},
	{"8Направлений": 0},
	{СледитьЗа: 0},
	{ОграничитьСценой: 0},
	{игрок: 0},
	{хп: 0},
	{ПолеЗрения: 0},
	{ДвижениеК: 0},
	{Твинанимация: 0},
	{зондбе: 0},
	{триггер: 0},
	{зондбеизгнание: 0},
	{стол: 0},
	{распятиеПутеводногоСвета: 0},
	{дверь1: 0},
	{дверь2: 0},
	{speed: 0},
	{Camera: 0},
	{распятиеЛюбопытногосвета: 0},
	{Гоблинооо: 0},
	{ОсновныеТекста: 0},
	{джефф: 0},
	{Прелавоклюбопытногокреста: 0},
	{Пуля: 0},
	{путеводныйсветсделалпиупиу: 0},
	{радио: 0},
	{Поворот: 0},
	{распятиевДействии: 0},
	{распятиевДействиилЛюбопытногоСвета: 0},
	{банкасчаевыми: 0},
	{окнодиалога: 0},
	{стул: 0},
	{текстГоблино: 0},
	{тень: 0},
	{туториалШаг2: 0},
	{хпзначок: 0},
	{скелетик: 0},
	{Подтекст: 0},
	{нажмитеЕчтобыподобрать: 0},
	{вМеню: 0},
	{Перетаскивание: 0},
	{Физика: 0},
	{коробкаИлиХзЧоЭтоВаще: 0},
	{монеткаВМультиплеере: 0},
	{мультиплеер: 0},
	{одиночнаяигра: 0},
	{скопировать: 0},
	{стрелка: 0},
	{выйти: 0},
	{статистика: 0},
	{настройки: 0},
	{дверь3: 0},
	{СохранитьПрофиль: 0},
	{Иконка2: 0},
	{Иконка1: 0},
	{Инвентарь: 0},
	{Прелавок: 0},
	{Прелавоккреста: 0},
	{ТекстаВМеню: 0},
	{куст: 0},
	{лампанапол: 0},
	{лианы1: 0},
	{мармеладка: 0},
	{стакан: 0},
	{Часы: 0},
	{ютуб: 0},
	{ягермейстер: 0},
	{Ячейка: 0},
	{ДверьИзлиан: 0},
	{Дерево: 0},
	{загрузка: 0},
	{scpПризрачныйсвет: 0},
	{WTF: 0},
	{WTF2: 0},
	{айди: 0},
	{АйдиКомнаты: 0},
	{Аудио: 0},
	{Браузер: 0},
	{БуферОбмена: 0},
	{времявигре: 0},
	{Деньги: 0},
	{дискорд: 0},
	{Имя: 0},
	{Индикатор: 0},
	{Клавиатура: 0},
	{Мышь: 0},
	{Никнейм: 0},
	{Советы: 0},
	{Список: 0},
	{Текст: 0},
	{текстВМеню: 0},
	{дохлыйЗондбе: 0},
	{светотлампы: 0},
	{Частицы: 0},
	{Частицы2: 0},
	{Частицы3: 0},
	{Частицы4: 0},
	{свет2откреста: 0},
	{осколок2: 0},
	{осколок: 0},
	{осколок3: 0},
	{opac: 0},
	{осколок4: 0},
	{осколок5: 0},
	{осколок6: 0},
	{свет3изгнание: 0},
	{темнота1: 0},
	{темнота2: 0},
	{свет4светлампы: 0},
	{свет5путеводныйсветлампа: 0},
	{Частицы5: 0},
	{Частицы6: 0},
	{светотснарядапутеводногосвета: 0},
	{свет5любопытныйсвет: 0},
	{светдверилюбопытносвета: 0},
	{Частицы7: 0},
	{свет5изгнаниеолбьктапутеводныйсвет: 0},
	{музыка: 0},
	{частицыВМеню: 0},
	{частицыВМеню2: 0},
	{Светмармелада1: 0},
	{Светмармелада2: 0},
	{ЧастицыМармеладук: 0},
	{ЧастицыМармеладук2: 0},
	{светотлампы2: 0},
	{Частицы8: 0},
	{заднийФон: 0},
	{достижения: 0},
	{магазин: 0},
	{ID: 0},
	{Names: 0},
	{пуля: 0},
	{игрокмультиплеер: 0},
	{Send: 0},
	{RoomName: 0},
	{Name: 0},
	{Multiplayer: 0},
	{Login: 0},
	{Info2: 0},
	{Go: 0},
	{Info: 0},
	{Create: 0},
	{ChatText: 0},
	{Chat: 0},
	{AdvancedRandom: 0},
	{зондбе2: 0},
	{зондбе3: 0},
	{зондбе4: 0},
	{активациязомби: 0},
	{кубикзакрытияОкна: 0},
	{мячик: 0},
	{опаснаястена: 0},
	{плитаНа50Денег: 0},
	{пресс1: 0},
	{пресс2: 0},
	{пресс3: 0},
	{пресс4: 0},
	{Руки: 0},
	{Спрайт: 0},
	{GamePush: 0},
	{витаминки: 0},
	{рывок: 0},
	{общаяГромкость: 0},
	{Спрайт4: 0},
	{Индикатор2: 0},
	{Кнопка: 0},
	{ГромкостьЗвуков: 0},
	{testtext: 0},
	{разделитель: 0},
	{топор: 0},
	{хитбокстопора: 0},
	{кровь: 0},
	{удар: 0},
	{Текст2: 0},
	{кресты: 0},
	{крестЛюбопытногоСвета: 0},
	{сообщения: 0},
	{заполненаяЛиБанкаСЧаевыми: 0},
	{меню: 0},
	{id: 0},
	{деньги: 0},
	{фулскрин: 0},
	{soundvolume: 0},
	{оружие: 0},
	{звукшагов: 0},
	{версия: 0},
	{discord: 0},
	{ChatLogin: 0},
	{ChatMessage: 0},
	{менюмультиплеер: 0},
	{кулдаункликов: 0},
	{перезарядка: 0},
	{GAMENAME: 0},
	{имя: 0},
	{совет: 0},
	{версияигры: 0},
	{smoothcamera: 0},
	{smoothcamera2: 0}
];

self.InstanceType = {
	пол: class extends self.ITiledBackgroundInstance {},
	стены: class extends self.ITiledBackgroundInstance {},
	лампа: class extends self.ISpriteInstance {},
	стенапрозрачная: class extends self.ITiledBackgroundInstance {},
	темнота: class extends self.ITiledBackgroundInstance {},
	каменнаяСтена: class extends self.ITiledBackgroundInstance {},
	каменныйпол: class extends self.ITiledBackgroundInstance {},
	стены2: class extends self.ITiledBackgroundInstance {},
	Переход: class extends self.ISpriteInstance {},
	Стена: class extends self.ITiledBackgroundInstance {},
	Трава: class extends self.ITiledBackgroundInstance {},
	СВет: class extends self.ITiledBackgroundInstance {},
	Камушки: class extends self.ITiledBackgroundInstance {},
	игрок: class extends self.ISpriteInstance {},
	зондбе: class extends self.ISpriteInstance {},
	триггер: class extends self.ISpriteInstance {},
	зондбеизгнание: class extends self.ISpriteInstance {},
	стол: class extends self.ISpriteInstance {},
	распятиеПутеводногоСвета: class extends self.ISpriteInstance {},
	дверь1: class extends self.ISpriteInstance {},
	дверь2: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	распятиеЛюбопытногосвета: class extends self.ISpriteInstance {},
	Гоблинооо: class extends self.ISpriteInstance {},
	ОсновныеТекста: class extends self.ITextInstance {},
	джефф: class extends self.ISpriteInstance {},
	Прелавоклюбопытногокреста: class extends self.ISpriteInstance {},
	путеводныйсветсделалпиупиу: class extends self.ISpriteInstance {},
	радио: class extends self.ISpriteInstance {},
	распятиевДействии: class extends self.ISpriteInstance {},
	распятиевДействиилЛюбопытногоСвета: class extends self.ISpriteInstance {},
	банкасчаевыми: class extends self.ISpriteInstance {},
	окнодиалога: class extends self.ISpriteInstance {},
	стул: class extends self.ISpriteInstance {},
	текстГоблино: class extends self.ITextInstance {},
	тень: class extends self.ISpriteInstance {},
	туториалШаг2: class extends self.ITextInstance {},
	хпзначок: class extends self.ISpriteInstance {},
	скелетик: class extends self.ISpriteInstance {},
	Подтекст: class extends self.ITextInstance {},
	нажмитеЕчтобыподобрать: class extends self.ISpriteInstance {},
	вМеню: class extends self.ISpriteInstance {},
	коробкаИлиХзЧоЭтоВаще: class extends self.ISpriteInstance {},
	монеткаВМультиплеере: class extends self.ISpriteInstance {},
	мультиплеер: class extends self.ISpriteInstance {},
	одиночнаяигра: class extends self.ISpriteInstance {},
	скопировать: class extends self.ISpriteInstance {},
	стрелка: class extends self.ISpriteInstance {},
	выйти: class extends self.ISpriteInstance {},
	статистика: class extends self.ISpriteInstance {},
	настройки: class extends self.ISpriteInstance {},
	дверь3: class extends self.ISpriteInstance {},
	СохранитьПрофиль: class extends self.ISpriteInstance {},
	Иконка2: class extends self.ISpriteInstance {},
	Иконка1: class extends self.ISpriteInstance {},
	Инвентарь: class extends self.ITextInstance {},
	Прелавок: class extends self.ISpriteInstance {},
	Прелавоккреста: class extends self.ISpriteInstance {},
	ТекстаВМеню: class extends self.ITextInstance {},
	куст: class extends self.ISpriteInstance {},
	лампанапол: class extends self.ISpriteInstance {},
	лианы1: class extends self.ISpriteInstance {},
	мармеладка: class extends self.ISpriteInstance {},
	стакан: class extends self.ISpriteInstance {},
	Часы: class extends self.ISpriteInstance {},
	ютуб: class extends self.ISpriteInstance {},
	ягермейстер: class extends self.ISpriteInstance {},
	Ячейка: class extends self.ISpriteInstance {},
	ДверьИзлиан: class extends self.ISpriteInstance {},
	Дерево: class extends self.ISpriteInstance {},
	загрузка: class extends self.ISpriteInstance {},
	scpПризрачныйсвет: class extends self.ISpriteInstance {},
	WTF: class extends self.ITextInstance {},
	WTF2: class extends self.ITextInstance {},
	айди: class extends self.ITextInstance {},
	АйдиКомнаты: class extends self.ITextInstance {},
	Аудио: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	БуферОбмена: class extends self.IInstance {},
	времявигре: class extends self.ITextInstance {},
	Деньги: class extends self.ITextInstance {},
	дискорд: class extends self.ISpriteInstance {},
	Имя: class extends self.ITextInstance {},
	Индикатор: class extends self.IProgressBarInstance {},
	Клавиатура: class extends self.IInstance {},
	Мышь: class extends self.IInstance {},
	Никнейм: class extends self.ITextInputInstance {},
	Советы: class extends self.ITextInstance {},
	Список: class extends self.IListInstance {},
	Текст: class extends self.ITextInstance {},
	текстВМеню: class extends self.ITextInstance {},
	дохлыйЗондбе: class extends self.ISpriteInstance {},
	светотлампы: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	Частицы3: class extends self.IParticlesInstance {},
	Частицы4: class extends self.IParticlesInstance {},
	свет2откреста: class extends self.ISpriteInstance {},
	осколок2: class extends self.ISpriteInstance {},
	осколок: class extends self.ISpriteInstance {},
	осколок3: class extends self.ISpriteInstance {},
	осколок4: class extends self.ISpriteInstance {},
	осколок5: class extends self.ISpriteInstance {},
	осколок6: class extends self.ISpriteInstance {},
	свет3изгнание: class extends self.ISpriteInstance {},
	темнота1: class extends self.ITiledBackgroundInstance {},
	темнота2: class extends self.ITiledBackgroundInstance {},
	свет4светлампы: class extends self.ISpriteInstance {},
	свет5путеводныйсветлампа: class extends self.ISpriteInstance {},
	Частицы5: class extends self.IParticlesInstance {},
	Частицы6: class extends self.IParticlesInstance {},
	светотснарядапутеводногосвета: class extends self.ISpriteInstance {},
	свет5любопытныйсвет: class extends self.ISpriteInstance {},
	светдверилюбопытносвета: class extends self.ISpriteInstance {},
	Частицы7: class extends self.IParticlesInstance {},
	свет5изгнаниеолбьктапутеводныйсвет: class extends self.ISpriteInstance {},
	музыка: class extends self.IParticlesInstance {},
	частицыВМеню: class extends self.IParticlesInstance {},
	частицыВМеню2: class extends self.IParticlesInstance {},
	Светмармелада1: class extends self.ISpriteInstance {},
	Светмармелада2: class extends self.ISpriteInstance {},
	ЧастицыМармеладук: class extends self.IParticlesInstance {},
	ЧастицыМармеладук2: class extends self.IParticlesInstance {},
	светотлампы2: class extends self.ISpriteInstance {},
	Частицы8: class extends self.IParticlesInstance {},
	заднийФон: class extends self.ITiledBackgroundInstance {},
	достижения: class extends self.ISpriteInstance {},
	магазин: class extends self.ISpriteInstance {},
	Names: class extends self.ITextInstance {},
	пуля: class extends self.ISpriteInstance {},
	игрокмультиплеер: class extends self.ISpriteInstance {},
	Send: class extends self.IButtonInstance {},
	RoomName: class extends self.ITextInputInstance {},
	Name: class extends self.ITextInputInstance {},
	Multiplayer: class extends self.IInstance {},
	Login: class extends self.IButtonInstance {},
	Info2: class extends self.ITextInstance {},
	Go: class extends self.IButtonInstance {},
	Info: class extends self.ITextInstance {},
	Create: class extends self.IButtonInstance {},
	ChatText: class extends self.ITextInputInstance {},
	Chat: class extends self.ITextInputInstance {},
	AdvancedRandom: class extends self.IInstance {},
	зондбе2: class extends self.ISpriteInstance {},
	зондбе3: class extends self.ISpriteInstance {},
	зондбе4: class extends self.ISpriteInstance {},
	активациязомби: class extends self.ISpriteInstance {},
	кубикзакрытияОкна: class extends self.ISpriteInstance {},
	мячик: class extends self.ISpriteInstance {},
	опаснаястена: class extends self.ISpriteInstance {},
	плитаНа50Денег: class extends self.ISpriteInstance {},
	пресс1: class extends self.ISpriteInstance {},
	пресс2: class extends self.ISpriteInstance {},
	пресс3: class extends self.ISpriteInstance {},
	пресс4: class extends self.ISpriteInstance {},
	Руки: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	витаминки: class extends self.ISpriteInstance {},
	рывок: class extends self.ISpriteInstance {},
	общаяГромкость: class extends self.ITextInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Индикатор2: class extends self.IProgressBarInstance {},
	Кнопка: class extends self.IButtonInstance {},
	ГромкостьЗвуков: class extends self.ISliderBarInstance {},
	testtext: class extends self.ITextInstance {},
	разделитель: class extends self.ISpriteInstance {},
	топор: class extends self.ISpriteInstance {},
	хитбокстопора: class extends self.ISpriteInstance {},
	кровь: class extends self.IParticlesInstance {},
	удар: class extends self.IParticlesInstance {},
	Текст2: class extends self.ITextInstance {}
}